### PR TITLE
Label click fix

### PR DESCRIPTION
**Pull request by royduin**
The `id` should be unique and the `for` is causing weird behavior when it's the same on every checkbox. The `handleChange()` is also present on the label so there is no need to have an `id` and `for`.

Another approach could be to remove the `@click` and use the `id` and `for`, but we need unique keys. The option keys could contain spaces so this way is safer.

### CODE REVIEW

**Comment by gkermer** [comment]
I have the same issue. Please accept this pull request.

**Comment by fourstacks** [comment]
Hi @royduin - thanks for the PR and sorry for the slow reply/merge

**Comment by royduin** [comment]
Thanks for merging and creating a new release 👍

**Comment by gkermer** [comment]
Thank you too

**Pull request merged**
