### PR TITLE
Adding tests to the package, add object, zero-index support

### PR DESCRIPTION
**Pull request by BrandonSurowiec**
Here's an outline of what I'm working on:

- [x] Default serialization test w/ expected component
- [x] Meta: options (assoc, values only), save formats, display and columns
- [x] Support object type casting from model
- [x] Support zero-indexed arrays
- [x] Loading of attribute from model when `$casts` is an
    - [x] assoc array: array, object, collection, string, nested json attribute
    - [x] numeric keyed array - array, object, collection, string, nested json attribute
    - [x] zero-based-index array - array, object, collection, string, string with 0 selected, nested json attribute
- [x] Saving of each save format:
   - [x] Comma separated string
   - [x] Only checked options
   - [x] Checked and unchecked options
- [x] Loading of each save format from the database.
- [x] Loading previously saved options when new ones have been since added and others removed 

Once the tests are written, it should be easier to refactor and add support for additional attribute casts, like `object`, or `collection.`

Hope this helps!

### CODE REVIEW

**Comment by fourstacks** [comment]
@BrandonSurowiec awesome - thanks very much indeed! 

Would be interested to see how you end up tackle the feature tests - if you can find a nice way of handling feature testing Nova fields then I'll try and apply that to my other field package - https://github.com/fourstacks/nova-repeatable-fields.

**Comment by BrandonSurowiec** [comment]
@fourstacks Field value tests from different casts types have been completed. I added support for object casting while I was at it: 

```
class User extends Model
{
    protected $casts = ['hobbies' => 'object'];
}
```

I started to write an integration test, but backtracked when I found an easier way in the existing Nova tests: https://github.com/laravel/nova/blob/master/tests/Feature/SelectTest.php

Seems like it will all be unit tests, which will keep it nice and simple.

**Comment by BrandonSurowiec** [comment]
@fourstacks If one tries to zero-index the options, it breaks the vue component to do the blank checkbox thing.

Input of  `[1,2]` from the database sends `[false,true,true]` instead of  `{"0": false, "1": true, "2": true}` to the Vue component with these field options:
```
Checkboxes::make('Hobbies')->options([
            'Archery', 
            'Painting', 
            'Running',
        ]);

```

Since zero-based keys are prone to breakage as options are moved around, renamed, or removed,  do you think the field should throw an exception when setting `->options()` with a zero-based index? OR would you want to support it, although undocumented? We can add support by doing something like this in PHP:

```
$value = (object)[true, false]; 
json_encode($value); // {"0": true, "1": false}
```

or in Vue:

```
var a = [true, false];

function toObject(arr) {
  var rv = {};
  for (var i = 0; i < arr.length; ++i)
    rv[i] = arr[i];
  return rv;
}

toObject(a); // {0: 1, 1: 2}
```

I would prefer the PHP version as it normalizes the expected output. Do you have any thoughts? (I can finish writing the test for the current implementation and then write a PR to add this functionality afterwards.)

[Edit] I ended up adding support for zero based index in the off-chance you are loading from the database but an id of 0 is a thing for some reason. This is all it took to make it work:

```
        if (! $value) {
            return json_encode((object)$this->withUnchecked([]));
        }

        if (is_array($value)) {
            if ($this->arrayIsAssoc($value)) {
				$value = $this->onlyChecked($value);
            }
            return json_encode((object)$this->withUnchecked($value));
        }


        return json_encode((object)$this->withUnchecked(explode(',', $value)));
```

**Comment by BrandonSurowiec** [comment]
I ended up adding support for zero-indexed arrays. (Had to handle a case where only 0 was selected in the string format). Works quite nicely :) Sorry if I'm cramming a bit too much into the PR, I can't help but fix and refactor a little once I get tests in place. Makes things so easy. Let me know if you want to be able to merge it in as is, or if you're okay with me to keep going.

**Comment by fourstacks** [comment]
Hey Brandon!  Great work on this PR - really appreciate you putting the time in.  I don't mind if the scope of the PR increases a little to catch edge cases like the zero-index one above.  Basically as long as I know roughly what's been done and why it's all good.

Just a heads up that I'm away until after the weekend so if you finish up this PR and I don't respond for a few days then don't worry it'll definitely get merged once I'm back!

**Comment by BrandonSurowiec** [comment]
Sounds like a plan, thanks!

**Comment by BrandonSurowiec** [comment]
Just pushed up the save format tests. What are your thoughts on a small refactor to this method?

```
    protected function onlyChecked($data)
    {
        return collect($data)
            ->filter(function ($isChecked) {
                return $isChecked;
            })
            ->map(function ($value, $key) {
                return $key;
            })
            ->values()
            ->all();
    }
```

into:

```
    protected function onlyChecked($data)
    {
        return collect($data)
            ->filter(function ($isChecked) {
                return $isChecked;
            })
            ->keys()
            ->all();
    }
```

The collection method `->keys()` is equivalent to `->map()->values()`. Also, `->filter()` would work just fine without any arguments, but it seems you added the closure for coder documentation, so I would lean towards keeping it if I changed the method.

Just a handful of tests left.

**Comment by BrandonSurowiec** [comment]
I realized I only had one more test to write, so I just finished it.

I did the small `->keys()` refactor mentioned above, keeping your filter. Just a note, the `getPackageProviders()` method in the `TestCase` isn't actually doing anything since there aren't any tests against the `FieldServiceProvider`. So that method can be deleted.

I'm going to mark this PR as ready for review.

**Comment by fourstacks** [comment]
@BrandonSurowiec Thanks very much for this - all looks great and I appreciate the sensible refactors like `->keys()`.  Think I'd probably be happy with that filter one going too as now you've pointed it out it's kinda bugging me!

Got a fairly busy day today but I'll do my best to take a look at all this tonight or tomorrow and get it merged in.

**Comment by BrandonSurowiec** [comment]
You're welcome! It was fun, and gave me a bit more knowledge about how Nova Fields work under the hood.

**Pull request merged**
