### PR TITLE
Support Collection

### PR DESCRIPTION
**Pull request by batFormat**
Add support `Illuminate\Support\Collection` type

### CODE REVIEW

**Comment by niladam** [comment]
@fourstacks -- can you tell me why this isn't being merged ? I think it's a really good addition to your package.

@batFormat - thank you for this PR dude!:)

**Comment by fourstacks** [comment]
Hi @niladam and @batFormat 

First up apologies for the delay - haven't had much time for OS stuff the past couple of months.

@batFormat - your PR looks fine but could you just give me a quick overview of why it's necessary?  Just want to understand what problem is solves so I can update the docs if necessary

**Comment by niladam** [comment]
From the looks of it -- it allows you to pass a collection. This way, you can basically use some models' collection as the options :)

**Comment by niladam** [comment]
Sadly, i'm having issues with packagist but i'm planning on testing this today.

**Comment by fourstacks** [comment]
Actually I hadn't thought about this but this PR is actually a little behind the latest version of Nova Checkboxes.  In v 0.1.0 the way data is passed to and from the vue component was changed.  See: https://github.com/fourstacks/nova-checkboxes/releases/tag/v0.1.0

@batFormat if you still feel like this PR would be useful, could you update to explain what problem is solves specifically and then update your PR by basing it on v 0.1.0

@niladam - Please check out v 0.1.0 to see if that does what you need.  If you want to use some attribute of a model that returns a collection as the options for the checkboxes then you can already do this doing something like this:

```
Checkboxes::make('Something')
    ->options($model->attribute_that_returns_collection->all())
```

**Comment by niladam** [comment]
@fourstacks Thank you. I didn't see that. Anyways, i'm having some issues where i cannot check the boxes. I'm unsure what's causing it.

If i use it on a separate model i'm not having this issue. Are there any known compatibility issues ?

**Comment by fourstacks** [comment]
@niladam - would you mind opening a separate issue with some more details for the issue you're describing above - would prefer not to derail this PR with other issues.  Thanks

**Comment by niladam** [comment]
You're right. Sorry for hijacking this.

**Comment by batFormat** [comment]
> @niladam - would you mind opening a separate issue with some more details for the issue you're describing above - would prefer not to derail this PR with other issues. Thanks

In my case, `$value` has collection type.

Therefore, if `$value` is a collection there is a reason to get a simple array from the collection, I think this does not violate the logic of the package.

**Comment by fourstacks** [comment]
@batFormat - thanks for updating the PR and sorry for such a long delay in getting onto this.  The update will be in the next release.

**Pull request merged**
